# Generated by Django 2.2.5 on 2022-01-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('b_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=45)),
                ('b_date', models.DateTimeField(default='CURRENT_TIMESTAMP')),
                ('contents', models.TextField()),
                ('view', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('c_no', models.AutoField(primary_key=True, serialize=False)),
                ('qna_date', models.DateTimeField()),
                ('contents', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Like_Board',
            fields=[
                ('l_no', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Like_Board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Photo_Board',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Photo_Board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QnA_Board',
            fields=[
                ('qna_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=45)),
                ('qna_yn', models.CharField(default='N', max_length=10)),
                ('qna_date', models.DateTimeField()),
                ('contents', models.TextField()),
                ('view', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'QnA_Board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Scrap',
                'managed': False,
            },
        ),
    ]
