# Generated by Django 2.2.5 on 2022-01-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0002_board_comment_like_board_photo_board_qna_board_scrap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
