# Generated by Django 2.2.5 on 2022-01-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0004_class_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_Board',
            fields=[
                ('tb_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=45)),
                ('category', models.CharField(max_length=45)),
                ('writer', models.CharField(max_length=45)),
                ('tb_date', models.DateTimeField(auto_now_add=True)),
                ('contents', models.TextField()),
                ('view', models.PositiveIntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Total_Board',
                'managed': False,
            },
        ),
    ]
