# Generated by Django 2.2.5 on 2022-01-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0006_auto_20220127_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_Like_Board',
            fields=[
                ('l_no', models.AutoField(primary_key=True, serialize=False)),
                ('writer', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Total_Like_Board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Total_Scrap',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('writer', models.CharField(max_length=45)),
                ('category', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Total_Scrap',
                'managed': False,
            },
        ),
    ]
